config:
  gitlab: 'https://gitlab.com'
  token: "gitlab private token"
  team: [dev1_login, dev2_login]
  groups:
    project-group-1:
      show_only_my: true # only token owner MRs will be shown, this option overrides show_only_team
      projects:
        my_amazing_repo:
          id: PROJECT_ID

    project-group-2:
      projects:
        another_repo:
          id: PROJECT_ID_2

    project-group-3:
      show_only_team: true # only team's MRs will be shown
      projects:
        another_repo:
          id: PROJECT_ID_2
